name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  ubuntu:
    name: Test
    runs-on: ubuntu-latest
    env: 
      LC_ALL: en_US.UTF-8   # For consistent sort order

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add current directory to path
      run: echo "$PWD" >> $GITHUB_PATH

    - name: Run shellcheck tests
      run: shellcheck repli

    - name: Start mock server
      run: docker run -d --rm --name mockly -v "$PWD/test/mockly:/app/mocks" -p 3000:3000 dannyben/mockly

    - name: Wait for mock server to boot
      run: timeout 30 bash -c 'until curl -sf http://localhost:3000; do sleep 1; done'

    - name: Run approval tests
      run: test/approve
